sudo: false
language: ruby
rvm:
  - 2.3
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
install:
  - gem install bundler
  - bundle --version
  - bundle install
script:
  - bundle exec rake test
